**Rationale** Hypothesis testing is foundational to the entire field of statistics. Without the Central Limit Theorem and hypothesis testing, we would not have modern day (social) science. In marketing, this is generally most important when doing A/B testing of ads. In this assignment, you will practice computing basic summary statistics and conducting hypothesis tests. 

[Datasets](https://drive.google.com/drive/folders/1D6D-zRU3oiP12c0dFMQjs66JDhBZBtax?usp=sharing) required:
1. [FB ad campaign data](https://drive.google.com/file/d/1JfwvumxS2oys8ZcQtsb8GGmeRfnkzFdy/view?usp=sharing).
1. [Starbucks Promos](https://drive.google.com/file/d/1W7x5_PU5KszT8mqXqqEmRfXuR8CRr1DX/view?usp=sharing)

# 1. (2 points) FB Ad campaigns

1. Use a groupby operation create a dataframe called `sumstats` consisting of the total impressions and clicks for each `xyz_campaign_id`.
1. Using `sumstats`, create a new column called `ctr` that represents the [click through rate](https://support.google.com/google-ads/answer/2615875?hl=en) for each campaign. Which campaign had the highest CTR?
1. Create a column for `sd` for standard deviation of the click through rate. 

Hint: Recall from the notes that the standard deviation of a binomial distribution with $Pr(Success) = p$ is $SD(p) = \sqrt{p(1-p)}$. So if the probability of a binary outcome (such as clicking on an ad) is observed to be .3, the standard deviation is $\sqrt{.3(.7)}=\sqrt{.21}$.

In [ ]:
# imports and mount google drive
import os, pandas as pd, numpy as np
from scipy import stats

from google.colab import drive
drive.mount('drive')

Mounted at drive


In [ ]:
# set the path to the datasets for A5
fpath = 'drive/MyDrive/Customer Data Analysis/'
os.listdir(fpath)

['MyNotes Mod1.ipynb',
 'A1 Treasure Love_Part1.ipynb',
 'A1_Part2.ipynb',
 'MyNotes_Mod2.ipynb',
 'A2 Programming Fundamentals.ipynb',
 'stores A data-set.csv',
 'stores data-set.csv',
 'stores B data-set.csv',
 'stores C data-set.csv',
 'sales data-set.csv',
 '9-8_notes2.ipynb',
 'Colab Notebooks',
 'quebec_yelp_reviews.csv',
 'quebec_biz.csv',
 'Quebec_dataset.csv',
 '9-8_notes.ipynb',
 'A3.ipynb',
 'Copy of InClass_Module_3.ipynb',
 'telecom_churn.csv',
 'renttherunway_final_data.json',
 'A4.ipynb',
 'Notes_Sept15.ipynb',
 '9 22_Notes.ipynb',
 '9-29_notes.ipynb',
 'facebook_ads.csv',
 'starbucks_promos.csv',
 'A4 F2021 - Visualization.ipynb',
 'A5.ipynb']

In [ ]:
# read in the facebook_ads.csv file as the dataframe variable named fb
fb = pd.read_csv(fpath + 'facebook_ads.csv')

In [ ]:
# Take a look at the first 5 rows
# Observe that each row represents 1 ad from 1 campaign and a target demographic group (age, gender, interest)
fb.head()

ad_id  xyz_campaign_id  ...  Total_Conversion Approved_Conversion
0  708746              916  ...                 2                   1
1  708749              916  ...                 2                   0
2  708771              916  ...                 1                   0
3  708815              916  ...                 1                   0
4  708818              916  ...                 1                   1

[5 rows x 11 columns]

In [ ]:
# use a groupby to create new dataframe, sumstats that tabulates the total clicks and impressions for each campaign.
# Generic groupby syntax: sumstats = df.groupby('groupbyvariable')[['summary_variable1', 'summary_variable2']].summaryfunction().reset_index()
# use the correct dataframe name, variables (i.e. column names) and summaryfunction

sumstats = fb.groupby('xyz_campaign_id')['Impressions', 'Clicks'].sum().reset_index()


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """


In [ ]:
# create a new column in sumstats called 'ctr' (short for click through rate)
# recall that ctr = clicks / impressions

sumstats['ctr']= sumstats['Clicks']/ sumstats['Impressions']

In [ ]:
# take a look at the whole sumstats dataframe

sumstats

xyz_campaign_id  Impressions  Clicks       ctr
0              916       482925     113  0.000234
1              936      8128187    1984  0.000244
2             1178    204823716   36068  0.000176

In [ ]:
# create a new column ctr_sd for the std. dev of the ctr (See hint above)
# pay attention to PEMDAS, esp. that you want to take the sqrt after computing p*(1-p)
# np.sqrt(x) returns the sqrt of some number x
# alternatively, x**.5 also returns the sqrt of x

p = sumstats.ctr
sumstats['ctr_sd'] = np.sqrt(p*(1-p))

In [ ]:
# take another look at the whole sumstats dataframe
# compare the ctr_std to calculating it by hand, make sure you did this correctly.

sumstats

xyz_campaign_id  Impressions  Clicks       ctr    ctr_sd
0              916       482925     113  0.000234  0.015295
1              936      8128187    1984  0.000244  0.015621
2             1178    204823716   36068  0.000176  0.013269

## Answer (edit this cell)
The campaign with the highest CTR is: **936**


# 2. (4 points) Hypothesis testing and confidence intervals

1. Compute the 95% confidence interval for the CTR for each campaign. Compare the confidence intervals of campaign 916 and 936. What can you conclude about the relative perfrmance of the 2 ads in the population (e.g. are they very different, similar, etc.)? How about 916 vs. 1178?

**916 v 936 results show the range in relative performance of the two ads is very similar. For 916 v 1179, though the range for 916 has a broader range, 1179's is more skewed to the right.**

1. Was campaign 936 statistically different compared to campaign 916? How about 936 vs. 1178? Use the `ttest_2sample` function from the notes. Remember, you must define it in your Colab session in order to use it (execute the cell w/ the function).

**No, it's not much different**

Given these statistical tests what would you recommend in terms of allocation of the ad budget? 

**I would recommend reallocating the budget, so more goes to the ads that do well.**

In [ ]:
sumstats

xyz_campaign_id  Impressions  Clicks       ctr    ctr_sd
0              916       482925     113  0.000234  0.015295
1              936      8128187    1984  0.000244  0.015621
2             1178    204823716   36068  0.000176  0.013269

In [ ]:
# use stats.norm.ppf([.025, .975], mean, std error)
# where mean is sample mean and std error is std dev / sqrt(obs) (from Central Limit Theorem)

#confidence interval for ad 916


stats.norm.ppf([.025, .975], 0.000234, 	0.015295/np.sqrt(482925))


array([0.00019086, 0.00027714])

In [ ]:
# confidence interval for ad 936

stats.norm.ppf([.025, .975], 0.000244, 0.015621/np.sqrt(8128187))


array([0.00023326, 0.00025474])

In [ ]:
# confidence interval for ad 1178

stats.norm.ppf([.025, .975], 0.000176, 0.013269/np.sqrt(204823716))


array([0.00017418, 0.00017782])

**Edit this cell**

1. (write 1-2 sentences to compare the confidence interval of 916 vs 936's CTR) **916 vs 936 have simular confidence intervals, where the range is not much different.**
1. (write 1-2 sentences to compare the confidence interval of 916 vs 1178's CTR) **1178 has a shorter range than 916, but 1178 is more skewed to the right.**

In [ ]:
# Use this custom funciton

def ttest_2sample(m1,sd1,N1,m2,sd2,N2, twotail = True, equalvar = False):
    """
    This function requires you tu supply:
    m1: mean of sample 1
    sd1: std. dev of sample 1
    N1: number of obs of sample 1
    m2: mean of sample 2
    sd2: std dev of sample 2
    N2: number of obs of sample 2

    Optional inputs:
    twotail = True (default) / False. If False, then 1 tail
    equalvar = True / False (default). If True, assumes equal population variance.
    """

    # The difference between equal and unequal variance is only in how to compute
    # the test statistic and degree of freedom.
    if equalvar:
        spsquare = ((N1-1)*sd1**2+(N2-1)*sd2**2)/(N1+N2-2) 
        T = (m1-m2)/np.sqrt(spsquare*(1/N1+1/N2))
        nu = N1+N2-2
    else:
        nu = (sd1**2/N1+sd2**2/N2)**2/((sd1**2/N1)**2/(N1-1)+(sd2**2/N2)**2/(N2-1)) # new degree of freedom
        T = (m1-m2)/(np.sqrt(sd1**2/N1+sd2**2/N2))
    
    # If the first mean is bigger, we need to do 1- cdf
    # Otherwise just compute cdf
    if m1>m2:
        pval = 1-stats.t.cdf(T, df = nu)
    else:
        pval = stats.t.cdf(T, df = nu)

    # return p values
    # If 2 tail, we must multiply by 2
    # otherwise we just return the computed pval
    if twotail == True:
        return pval*2
    else:
        return pval

In [ ]:
# run a 2 tail 2 sample t-test to compare the population CTRs for 936 and 916

m1= 0.000244
sd1= 0.015621
N1= 8128187

m2= 0.000234
sd2= 0.015295
N2= 482925


ttest_2sample(m1,sd1,N1,m2,sd2,N2, twotail= True, equalvar= False)

0.659290373515292

In [ ]:
# run a 2 tail 2 sample t-test to compare the population CTRs for 936 and 1178

m1= 0.000244
sd1= 0.015621
N1= 8128187

m2= 0.000176
sd2= 0.013269
N2= 204823716

ttest_2sample(m1,sd1,N1,m2,sd2,N2, twotail = True, equalvar = False)

0.0

**Edit this cell to answer**

When comparing 916 and 936, the P-Value is very high and has no significance compared to the second comparison test with 936 to 1178. The company should reallocate their budget to put more money into the 916, to bring the P-Value closer to zero and more significant.


# 3. (4 points)

Using the Starbucks dataset, conduct an appropriate statistical test to determine:
1. Is there any statistically appreciable difference in the redemption rates of BOGO vs. Discount promotions? **No, the P-Value is high, meaning there is not statistical signinficance in their comparison.**
1. Among those who redeemed an offer and reported their income, is there any statistical difference in the average income associated with BOGO vs. discount redemptions? Note that not every observation reports income (select only the observations that do). **As the P-Value is smaller, there is a less of a statistical difference than there was with the first comparison.**

In [ ]:
# read in the starbucks_promos.csv file as the dataframe variable named sb, use index_col = 0 option

sb = pd.read_csv(fpath + 'starbucks_promos.csv', index_col = 0)

In [ ]:
# preview first 5 rows to get a sense of the contents of the dataframe
# note that each observation represents an offer received by a customer

sb.head()

uid           event  ...  redeem_time redeemed
1  0020c2b971eb4e9188eac86d93036a77  offer received  ...         54.0        1
4  005500a7188546ff8a767329a2f7c76a  offer received  ...          NaN        0
5  0056df74b63b4298809f0b375a304cf4  offer received  ...        132.0        1
6  00715b6e55c3431cb56ff7307eb19675  offer received  ...         12.0        1
8  00840a2ca5d2408e982d56544dc14ffd  offer received  ...        540.0        1

[5 rows x 17 columns]

In [ ]:
# select the redeemed column for discount offers, name this data the variable disc

disc = sb.loc[sb.offer_type =='discount', 'redeemed']

In [ ]:
# select the reemed column for buy one get one (bogo) offers, name this data the variable bogo

bogo = sb.loc[sb.offer_type=='bogo', 'redeemed']

In [ ]:
# use stats.ttest_ind to test whether the 2 types of offers yield different redemption rates

stats.ttest_ind(disc, bogo, equal_var = False)[1]

6.641774929557673e-67

In [ ]:
# Select the income column for those who redeemed the BOGO offer, call this the variable bogo_income
# note you need to use 3 condtitions for the row selection: one for redeemed, one for bogo offer, and one for income is not missing
# FYI: dataframe.somecolumn.notnull() is the Boolean evaluation for whether the somecolumn is not missing data

bogo_income = sb.loc[(sb.redeemed == 1)&(sb.offer_type == 'bogo')&(sb.income.notnull()), 'income']

In [ ]:
# Select the income column for those who redeemed the discount offer, call this the variable disc_income
# note you need to use 3 condtitions for the row selection: one for redeemed, one for discount offer,  and one for income is not missing
# FYI: dataframe.somecolumn.notnull() is the Boolean evaluation for whether the somecolumn is not missing data

disc_income = sb.loc[(sb.redeemed == 1)&(sb.offer_type == 'discount')&(sb.income.notnull()), 'income']

In [ ]:
# What is the average income for bogo redeemers (bogo_income.mean())?

bogo_income.mean()

70114.8559593297

In [ ]:
# What is the average income for discount redeemers?

disc_income.mean()

68617.39130434782

In [ ]:
# use stats.ttest_ind to test whether the average income of the redeemers of the 2 offer types are different

stats.ttest_ind(bogo_income, disc_income, equal_var = False)[1]

2.283574816464658e-10

**Edit this cell**
1. The first t-test showed there was little to no coorelation between the two categories and whther they were redeemed or not.
1. Discounts and bogo offers were redeemed far more often depending on the income of the shopper. The t-test showed there was a very strong coorelation between the two. 